image: fedora:latest

variables:
  DEPENDENCIES: >-
    gcc git libtool make bzip2 libusb-devel
  FUZZING_DEPENDENCIES: >-
    clang libcxx-devel compiler-rt
  MINGW_DEPENDENCIES: >-
    mingw64-gcc mingw64-pkg-config mingw64-glib2 mingw64-libusbx

build_stable:
  before_script:
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - ./autogen.sh --prefix=/usr
    - make
    - make check
    - make install
    - make distcheck

build_fuzzing:
  before_script:
    - dnf install -y --nogpgcheck $DEPENDENCIES $FUZZING_DEPENDENCIES
  script:
    - >-
      ./autogen.sh --prefix=/usr --enable-fuzzing \
        CC='clang -fsanitize=fuzzer-no-link -fsanitize=address' \
        CXX='clang++ -fsanitize=fuzzer-no-link -fsanitize=address' \
        LIB_FUZZING_ENGINE='-fsanitize=fuzzer'
    - make
    - make check
    - make install
    - make distcheck

windows:
  before_script:
    - dnf install -y --nogpgcheck $DEPENDENCIES $MINGW_DEPENDENCIES

  script:
    - ./autogen.sh --prefix=/usr
    - mingw64-configure
    - mingw64-make
    - mingw64-make install
