image: fedora:latest

variables:
  DEPENDENCIES: >-
    gcc clang meson ninja-build git libtool make bzip2 libusb-devel glib2-devel
  FUZZING_DEPENDENCIES: >-
    clang libcxx-devel compiler-rt
  MINGW_DEPENDENCIES: >-
    mingw64-gcc mingw64-pkg-config mingw64-glib2 mingw64-libusbx

# Check if can build with and without usbredirect
stable:
  before_script:
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - ./autogen.sh --prefix=/usr --with-tools
    - make
    - make check
    - make install
    - make distcheck

    - git clean -xfd
    - ./autogen.sh --prefix=/usr --without-tools
    - make
    - make check
    - make install

    - meson . _build -Dfuzzing=disabled -Dtools=enabled
    - ninja -C _build
    - ninja -C _build dist

.fuzzing_base:
  resource_group: fuzzing
  before_script:
    - dnf install -y --nogpgcheck $DEPENDENCIES $FUZZING_DEPENDENCIES
    - export CC='clang -fsanitize=fuzzer-no-link -fsanitize=address'
    - export CXX='clang++ -fsanitize=fuzzer-no-link -fsanitize=address'

fuzzing_autoconf:
  extends: .fuzzing_base
  script:
    - >-
      ./autogen.sh --prefix=/usr --enable-fuzzing \
        LIB_FUZZING_ENGINE='-fsanitize=fuzzer'
    - make
    - make check
    - make install
    - make distcheck

fuzzing_meson:
  extends: .fuzzing_base
  script:
    - export LIB_FUZZING_ENGINE=-fsanitize=fuzzer
    - export OUT=/tmp/fuzzer
    - ./build-aux/oss-fuzz.sh

fuzzing_standalone:
  extends: .fuzzing_base
  script:
    - export LIB_FUZZING_ENGINE=standalone
    - export OUT=/tmp/fuzzer-standalone
    - ./build-aux/oss-fuzz.sh

windows:
  before_script:
    - dnf install -y --nogpgcheck $DEPENDENCIES $MINGW_DEPENDENCIES

  script:
    - ./autogen.sh --prefix=/usr --enable-tools
    - mingw64-configure
    - mingw64-make
    - mingw64-make install

    - mkdir _win_build && cd _win_build
    - mingw64-meson -Dtools=enabled
    - ninja
